### ISSUE TITLE
fontawesome-free not found

### ISSUE THREAD

**Issue by Robokishan** [MirrorBottle/react-argon-dashboard#1]
Just doing yarn and then yarn start gives me following error
`Failed to compile.

./src/index.js
Module not found: Can't resolve './assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' in '/Users/kishan/Work/Tests/typescript-argon-template/src'`

**Comment by MirrorBottle** [comment]
Did you run `yarn install` first before `yarn start`?

**Comment by Robokishan** [comment]
Yes i did. basically i type `yarn` instead of `yarn install` does it make any difference ?

**Comment by Robokishan** [comment]
but i checked on github repo `assets/vendor/@fortawesome/fontawesome-free/css/all.min.css` is not there

**Comment by MirrorBottle** [comment]
Sorry, i forgot to change `index.js` inside the folder for the package, you could install the `@fortawesome/fontawesome-free` and change it manually to `import "@fortawesome/fontawesome-free/css/all.min.css"`

**Comment by Robokishan** [comment]
will this package work ?
https://www.npmjs.com/package/@fortawesome/fontawesome-free

**Comment by MirrorBottle** [comment]
Yup, i did check that i already add the package when you run `yarn install` so i think you just need to change the index.js just like i said before

**Comment by Robokishan** [comment]
but will index.js work ? since it is typescript template

**Comment by Robokishan** [comment]
still having lots of bugs. i will try to fix and make a PR

**Comment by MirrorBottle** [comment]
Really appreciate it. This is my first template, so yeah, there is a lot to be fixed i suppose

**Comment by Robokishan** [comment]
Yeah, sure I will try to fix it. I really appreciate your work

**Comment by MirrorBottle** [comment]
A lot of thanks for you. I'll do some bug-fixing too right away.

So can I close this or just let it open?

**Comment by Robokishan** [comment]
you can close this
